import { NextResponse } from "next/server";
import { MemberRole, Prisma } from "@prisma/client"; // Import Prisma types
import { v4 as uuidv4 } from "uuid";
import { currentProfile } from "@/lib/current-profile";
import { db } from "@/lib/db";

export async function POST(req: Request) {
  try {
    const body = await req.json();
    const profile = await currentProfile();

    if (!profile) {
      return new NextResponse("Unauthorized", { status: 401 });
    }

    // Extract topics from the request body
    const topics: string[] = [];
    let i = 1;
    while (body[`topic${i}`]) {
      topics.push(body[`topic${i}`]);
      i++;
    }

    // Create the server first to get its ID
    const server = await db.server.create({
      data: {
        profileId: profile?.id,
        name: body["name"],
        imageUrl: body["imageUrl"],
        description: body["description"],
        departement: body["departement"],
        location: body["location"],
        inviteCode: uuidv4(),
        channels: {
          create: [
            { name: "general", profileId: profile?.id }
          ]
        },
        members: {
          create: [
            { profileId: profile?.id, role: MemberRole.ADMIN }
          ]
        }
      }
    });

    // Map topics to the Prisma format and include the server ID
    const topicCreateData: Prisma.ServerTopicCreateInput[] = topics.map((topic: string) => ({
      name: topic,
      server: { connect: { id: server.id } } // Use the server ID generated by the system
    }));

    // Create the topics associated with the server
    for (const topic of topicCreateData) {
      await db.serverTopic.create({
        data: {
          name: topic.name,
          server: { connect: { id: server.id } }
        }
      });
    }

    return NextResponse.json(server);
  } catch (error) {
    console.log("[SERVERS_POST]", error);
    return new NextResponse("Internal Error", { status: 500 });
  }
}
